name: CI

on: [push]

jobs:
  build:
    name: Install Go
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - name: 'Setup Go 1.20.x'
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
          cache-dependency-path: go.sum
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: |
          go get ./...

  check-golangci:
    name: Run golangci-lint
    needs:
      - build
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    steps:
      - name: "Run golangci lint"
        run: golangci-lint run ./... -v
