name: Build & Run lint

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  golangci-lint:
    name: Run lint
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53