name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Install Go
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - name: 'Setup Go 1.20'
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: go.sum
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: |
          go get ./...
